name: nextcloud
version: 1.0.10
description: A Nextcloud client for dart which can use WebDav and the OCS API
homepage: https://github.com/jld3103/nextcloud

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  xml: any
  intl: any
  dio: ">=3.0.0 <4.0.0"