name: nextcloud
version: 1.0.9
description: A Nextcloud client for dart which can use WebDav and the OCS API
homepage: https://github.com/jld3103/nextcloud

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  xml: ^3.6.1
  intl: ^0.16.0
  dio: ^3.0.7